### PR TITLE
Use `dry-transformer` for application functions

### PR DESCRIPTION
**Pull request by jodosha**
This change aims to replace `transproc` which is deprecated.

### CODE REVIEW

**Review by solnic — APPROVED** [review]

**Comment by solnic** [comment]
Should we come up with some conventional usage here? ie have a builtin component that provides common transformation functions? /cc @timriley

**Comment by jodosha** [comment]
@solnic Isn't that already happening by importing Array and Hash common functions? 🤔

**Comment by timriley** [comment]
I think @solnic was suggesting that we have offer a built-in place for these data transformers as part of the Hanami framework, rather than generating a file into the apps. Do I understand you correctly, @solnic?

I wonder if we could actually do a bit of both for starters:

1. We remove this file from what we generate. Everyone's needs/preferences for data transformation may be different, and something like this is easy to drop in yourself.
2. Then we see how things go with 2.0 and perhaps consider an out-of-the-box data transformer component for a 2.1 or later release.

What do you think?

**Comment by solnic** [comment]
> Do I understand you correctly, @solnic?

Correct 🙂 

@timriley I'm OK with postponing this until after 2.0 final. A `Functions` file may be too suggestive at this point.

**Comment by timriley** [comment]
Cool! Sounds like the next action here should be to remove it for now.

**Pull request merged**
