### PR TITLE
Fix the CSRFProtection constant not being loaded by zeitwerk

### PR DESCRIPTION
**Pull request by swilgosz**
Resolves: #16

### CODE REVIEW

**Comment by timriley** [comment]
Thanks again @swilgosz! While I'm not in love with acronyms needing to be downcased like this in their constant names, for the time being while this file lives inside the template app (it will eventually move back into Hanami proper), I'm good with the simplest fix :)

**Comment by solnic** [comment]
@timriley speaking of which, I have a hack that overrides default inflector - do we have a public API for setting it up?

**Comment by timriley** [comment]
@solnic Hanami's default inflector is already configurable, and we also configure Zeitwerk with it. This is exercised in the tests introduced in https://github.com/hanami/hanami/pull/1100 (see the `NBAJam` usage in the first example in `spec/new_integration/container/autoloader_spec.rb`).

Is that what you're looking for? Otherwise, let me know more detail and we can work things out :)

**Comment by solnic** [comment]
@timriley yes that's exactly what I needed, ty!

**Pull request merged**
